### ISSUE TITLE
Any plans to advance it?

### ISSUE THREAD

**Issue by zloirock** [leobalter/proposal-setmap-offrom#33]
The previous time this proposal was presented to TC39 7+ years ago.

Are there any plans to advance it or is this proposal dead?

**Comment by bakkot** [comment]
This is still in my queue to get back to, but it's a lower priority for me than Math.sum, base64, and async iterators. I think some of the work on the set methods proposal has clarified some of the design space here (specifically, these methods can simply ignore subclasses, following set methods and discussion [here](https://matrixlogs.bakkot.com/TC39_General/2022-09-28), which gives us https://github.com/tc39/proposal-setmap-offrom/issues/16 for free). Hopefully it will be relatively straightforward once I have time for it.

Incidentally Math.sum may end up motivating a follow-on proposal for summing an iterable (rather than varargs), which might be called something like Math.sumFrom; if we do end up doing that I think this would make a nice follow-on to that as well.
